export { colors } from './colors'
export { spacing } from './spacing'
export { typography } from './typography'
export { borders } from './borders'
export { shadows } from './shadows'

export type { Colors } from './colors'
export type { Spacing } from './spacing'
export type { Typography } from './typography'
export type { Borders } from './borders'
export type { Shadows } from './shadows'